# Generated by Django 3.2.22 on 2023-10-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_planer', '0003_userpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='inhalt',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='titel',
            new_name='title',
        ),
    ]
