# Generated by Django 3.2.22 on 2023-10-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_planer', '0004_auto_20231018_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
